services:
  postgres:
    image: postgres:13-alpine

    ports:
      - "5432:5432"

    environment:

      - POSTGRES_DB=app
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password


  mysql:
    image: mysql:8.0
    ports:
          - '3306:3306'

    environment:
          - MYSQL_RANDOM_ROOT_PASSWORD=yes
          - MYSQL_DATABASE=app
          - MYSQL_USER=user
          - MYSQL_PASSWORD=password


  gate-simulator:
    build: ./gate-simulator  # Путь к папке с проектом эмулятора
    command: npm start        # Команда для запуска эмулятора
    volumes:
      - ./gate-simulator:/usr/src/app  # Монтирование исходного кода
    working_dir: /usr/src/app           # Рабочая директория внутри контейнера